### ISSUE TITLE
Windows should have a border

### ISSUE THREAD

**Issue by StrikerTwo** [kreischweide/metrothing#18]
It's really hard to see where the app window is if you have something with a white background behind it. See screenshot.

![image](https://cloud.githubusercontent.com/assets/6770084/6820388/c1c159aa-d2ce-11e4-8a0f-df17dd613f2a.png)

**Comment by kreischweide** [comment]
Hm this is strange, normally they have one. You are using Windows 8 oder 8.1 right?

**Comment by StrikerTwo** [comment]
2012R2 actually, but with the Desktop Experience features installed.

**Comment by kreischweide** [comment]
Ah that might be why the Aero-Shadow is not rendered. I will switch it to a normal DropShadow in the next release, that will help hopefully.

**Comment by kreischweide** [comment]
If you want you can try again. If you have installed the installer-version, jsut shut it down, restart it and see if it updates to the latest version (may take 1 minute, you will se a orange bar at the bottom if it happend). Otherwise replace the files.

**Comment by StrikerTwo** [comment]
Looking good, thanks! Didn't try the auto-update though, just got the new installer from github.
