### ISSUE TITLE
Device name does not show

### ISSUE THREAD

**Issue by StrikerTwo** [kreischweide/metrothing#19]
I have added two devices, but which is which?

![image](https://cloud.githubusercontent.com/assets/6770084/6820467/9b019590-d2cf-11e4-81d3-a568910c2279.png)

**Comment by kreischweide** [comment]
Did you enter a custom label or just left it empty as you added the instances?

**Comment by kreischweide** [comment]
Ah I see where it happens, will be fixed next version. Thanks for reporting!

**Comment by kreischweide** [comment]
Try again!

**Comment by StrikerTwo** [comment]
Works, thank you!
